compressionLevel: 0

enableGlobalCache: false

enableImmutableInstalls: false

enableInlineBuilds: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
